Project/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views as app_view
from django.contrib.auth import views as auth
from django.contrib.auth import views as auth_views
from app.views import ResetPasswordView
from django.conf import settings
from django.conf.urls.static import static
 
urlpatterns = [
 
    path('admin/', admin.site.urls),
 
    ##### user related path########################## 
    path('', include('app.urls')),
    path('index1/', app_view.index1, name='index1'),
    path('login/', app_view.Login, name ='login'),
    path('logout/', app_view.logout_view, name='logout'),
    path('register/', app_view.register, name ='register'),
    path('password-reset/', ResetPasswordView.as_view(template_name='app/password_reset.html'), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='app/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='app/password_reset_complete.html'),
         name='password_reset_complete'), 
 
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path, include
from django.conf import settings
from . import views
from django.conf.urls.static import static
 
urlpatterns = [
         path('', views.index, name ='index'),
         path('about/', views.about, name ='about'),
         path('services/', views.services, name ='services'),
         path('terms/', views.terms, name ='terms'),
         path('privacypolicy/', views.privacypolicy, name ='privacypolicy'),
         path('add_file/', views.add_file, name='add_file'),
         path('file/<uuid:public_url>/', views.file_detail, name='file_detail'),
         path("contact/", views.contact, name="contact"),
         path('success/', views.success, name='success'),
         path('upload/', views.upload_image, name='upload_image'),
         path('image_list/', views.image_list, name='image_list'),
         path('image/<int:image_id>/delete/', views.delete_image, name='delete_image'),
         path('image/<int:image_id>/edit/', views.edit_image, name='edit_image'),
         path('files/<int:file_id>/edit/', views.edit_file, name='edit_file'),
         path('files/<int:file_id>/delete/', views.delete_file, name='delete_file'),
         path('upload_pdf', views.upload_pdf, name='upload_pdf'),
         path('pdf_list', views.pdf_list, name='pdf_list'),    
         path('pdfs/<int:pdf_id>/delete/', views.delete_pdf, name='delete_pdf'),
         path('pdfs/<int:pdf_id>/edit/', views.edit_pdf, name='edit_pdf'),
]

app/models.py
# app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from uuid import uuid4

class File(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    public_url = models.CharField(max_length=100, unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.public_url:
            self.public_url = str(uuid4())[:8]  # Generate a unique URL if not provided
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('file_detail', kwargs={'public_url': self.public_url})

class UploadedPDF(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    pdf_file = models.FileField(upload_to='pdf_files/')
    public_url = models.CharField(max_length=100, blank=True, null=True)

from django.db import models

class UploadedImage(models.Model):
    # Your existing fields
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    image_file = models.ImageField(upload_to='images/')
    
    # Add the public_url field
    public_url = models.URLField(blank=True)

app/forms.py
# accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
 
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserRegisterForm(UserCreationForm):
    username = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'input', 'placeholder': 'Enter your username'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'input', 'placeholder': 'Enter your email'}))
    first_name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'input', 'placeholder': 'Enter your firstname'}))
    last_name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'input', 'placeholder': 'Enter your lastname'}))
    password1 = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'class': 'input', 'placeholder': 'Enter your password'}))
    password2 = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'class': 'input', 'placeholder': 'Enter your password confirmation'}))
    class Meta:
        model = User
        fields = ['username','email', 'first_name','last_name','password1','password2']

# myproject/accounts/forms.py

from django import forms
from .models import File

class FileForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ['title', 'content']
        
class ContactForm(forms.Form):
    name = forms.CharField(label='Your Name', max_length=100)
    email = forms.EmailField(label='Your Email')
    message = forms.CharField(label='Your Message', widget=forms.Textarea)

from .models import UploadedPDF

class UploadPDFForm(forms.ModelForm):
    class Meta:
        model = UploadedPDF
        fields = ['title', 'pdf_file']

from django import forms
from .models import UploadedImage

class UploadImageForm(forms.ModelForm):
    class Meta:
        model = UploadedImage
        fields = ['name', 'image_file', 'public_url']

app/templates/app/add_file.html
{% extends 'app/index.html' %}
{% load crispy_forms_tags %}
{% block start %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ title }}</title>
    <style>
        /* Flex container */
        /* Horizontally center the content */
        .justify-center {
            justify-content: center;
        }

        /* Vertically center the content */
        .items-center {
            align-items: center;
        }

        /* Add padding on the x-axis */
        .flex {
            display: flex;
            justify-content: center; /* Horizontally center the content */
            align-items: center; /* Vertically center the content */
        }

        /* Container styles */
        .container {
            width: 100%; /* Full width */
            max-width: 500px; /* Maximum width for larger screens */
            padding-top: 3%;
        }

        /* Style for the label */
        .label {
            display: block;
            margin-bottom: 5px;
            font-size: 14px;
            font-weight: bold;
        }

        /* Style for the input */
        .input {
            background-color: transparent;
            border: 1px solid #ced4da;
            border-radius: 0.25rem;
            font-size: 14px;
            padding: 10px;
            width: 100%;
            transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
        }

        /* Focus styles for the input */
        .input:focus {
            border-color: #80bdff;
            outline: 0;
            box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
        }
    </style>
</head>
<body>
    <div class="wrapper">
        <div class="content">
  <div class="flex">
    <div class="container">
        <form method="post">
          {% csrf_token %}
        <h3>Create File</h3>
          <div class="mb-3">
            <label for="id_title" class="label">File Name:</label>
            <input type="text" id="id_title" name="title" class="input" placeholder="Enter your filename" required>
        </div>
          <div>
            <label for="id_content" class="label">Content:</label>
            <textarea id="id_content" name="content" rows="10" class="input" placeholder="Enter your content here ...." required></textarea>
          </div>
          <button type="submit" class="btn">Publish file</button>
        </form>
    </div>
    </div>
        </div></div>
</body>
</html>

{% endblock start %}

app/templates/app/delete_image_confirm.html
{% extends 'app/index.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% block start %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Image</title>
</head>
<body>
    <h1>Delete Image</h1>
    <p>Are you sure you want to delete this image?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Delete</button>
    </form>
</body>
</html>
{% endblock start %}

app/templates/app/edit_file.html
{% extends 'app/index.html' %}
{% load crispy_forms_tags %}

{% block start %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ title }}</title>
    <style>
       /* Horizontally center the content */
       .justify-center {
            justify-content: center;
        }

        /* Vertically center the content */
        .items-center {
            align-items: center;
        }

        /* Add padding on the x-axis */
        .flex {
            display: flex;
            justify-content: center; /* Horizontally center the content */
            align-items: center; /* Vertically center the content */
        }

        /* Container styles */
        .container {
            width: 100%; /* Full width */
            max-width: 500px; /* Maximum width for larger screens */
            padding-top: 3%;
        }

        /* Style for the label */
        .label {
            display: block;
            margin-bottom: 5px;
            font-size: 14px;
            font-weight: bold;
        }

        /* Style for the input */
        .input {
            background-color: transparent;
            border: 1px solid #ced4da;
            border-radius: 0.25rem;
            font-size: 14px;
            padding: 10px;
            width: 100%;
            transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
        }

        /* Focus styles for the input */
        .input:focus {
            border-color: #80bdff;
            outline: 0;
            box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
        }

    </style>
</head>
<body>
    <div class="wrapper">
        <div class="content">
    <div class="flex">
        <div class="container">
            <form method="post">
                {% csrf_token %}
                <h3>{{ form_title }}</h3>
                <div class="mb-3">
                    <label for="id_title" class="label">File Name:</label>
                    <input type="text" id="id_title" name="title" value="{{ file.title }}" class="input" placeholder="Edit your filename" required>
                </div>
                <div>
                    <label for="id_content" class="label">Content:</label>
                    <textarea id="id_content" name="content" rows="10" class="input" placeholder="Edit your content" required>{{ file.content }}</textarea>
                </div>
                <button type="submit" class="btn">{{ button_label }}</button>
            </form>
        </div>
    </div>
        </div></div>
</body>
</html>
{% endblock start %}

app/templates/app/edit_pdf.html
{% extends 'app/index.html' %}
{% load crispy_forms_tags %}

{% block start %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ title }}</title>
    <style>
       /* Horizontally center the content */
       .justify-center {
            justify-content: center;
        }

        /* Vertically center the content */
        .items-center {
            align-items: center;
        }

        /* Add padding on the x-axis */
        .flex {
            display: flex;
            justify-content: center; /* Horizontally center the content */
            align-items: center; /* Vertically center the content */
        }

        /* Container styles */
        .container {
            width: 100%; /* Full width */
            max-width: 500px; /* Maximum width for larger screens */
            padding-top: 3%;
        }

        /* Style for the label */
        label {
            display: block;
            margin-bottom: 5px;
            font-size: 14px;
            font-weight: bold;
        }

        /* Style for the input */
        input {
            background-color: transparent;
            border: 1px solid #ced4da;
            border-radius: 0.25rem;
            font-size: 14px;
            padding: 10px;
            width: 100%;
            transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
        }

        /* Focus styles for the input */
        input:focus {
            border-color: #80bdff;
            outline: 0;
            box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
        }

    </style>
</head>
<body>
    <div class="wrapper">
        <div class="content">
    <div class="flex">
        <div class="container">
  <h2>Edit PDF</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
      <label for="id_title">Title:</label>
    <input type="text" name="title" value="sfl s" maxlength="100" placeholder="Edit your pdf name" required="" id="id_title">
    </div>
    <div class="mb-3">
    <label>Current Pdf file:
    <a href="/pdf_files/2000031715_capstone1.pdf">pdf_files/2000031715_capstone1.pdf</a></label>
Change:
<input type="file" name="pdf_file" id="id_pdf_file">
  </div>
    <button class="btn" type="submit">Save Changes</button>
  </form>
        </div>
    </div>
        </div></div>
  </body>
  </html>
  {% endblock start %}

app/templates/app/file_detail.html
<!-- myproject/accounts/templates/accounts/blog_detail.html -->

{% load crispy_forms_tags %}
{% block start %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{title}}</title>
  
<style>
  /* blog_detail.css */

/* Container for blog details */
.container {
 max-width: 800px;
 margin: 0 auto; /* Center the container horizontally */
 padding: 20px;
 text-align: center; /* Center the text inside the container */
}

/* Heading for blog title */
h2 {
 font-size: 24px;
 color: #333;
 margin-bottom: 10px;
}

/* Paragraph for blog content */
p {
 font-size: 16px;
 color: #666;
 line-height: 1.6;
 margin-bottom: 20px;
}

</style>
</head>
<body> 

<div class="container">
    <h2>{{ file.title }}</h2>
    <p>{{ file.content }}</p>
</div>
{% endblock start %}

</body>
</html>

app/templates/app/image_list.html
{% extends "app/index.html" %}
{% load crispy_forms_tags %}
{% block start %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <style>
        /* Your CSS styles here */
        /* Define card layout */
        .card-container {
            display: flex;
            flex-wrap: wrap;
            gap: 1rem;
            margin-top: 1rem;
        }

        .card {
            flex: 0 1 calc(50% - 0.5rem); /* Adjust card width */
            border-radius: 0.375rem;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            overflow: hidden;
        }

        .card-body {
            padding: 1rem;
        }

        .card-title {
            font-size: 1.25rem;
            margin-bottom: 0.5rem;
        }

        .delete-btn {
            color: #c53030; /* Adjust delete button text color */
        }

        .delete-btn:hover {
            color: #fff;
            background-color: #c53030; /* Adjust delete button background color on hover */
        }

        .edit-btn {
            color: #3182ce; /* Adjust edit button text color */
        }

        .edit-btn:hover {
            color: #fff;
            background-color: #3182ce; /* Adjust edit button background color on hover */
        }

        .download-btn {
            color: #10b981; /* Adjust download button text color */
        }

        .download-btn:hover {
            color: #fff;
            background-color: #10b981; 
        }/* Adjust download button background color on hover */

    </style>
</head>
<body>
    <div class="container">
    <div class="wrapper">
        <div class="content">
    <h1>All Images</h1>
    <div class="card-container">
        {% for image in images %}
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title">{{ image.name }}</h2>
                        <p>public url: {{ request.scheme }}://{{ request.get_host }}{{ image.image_file.url }}</p>
                        <button class="copy-btn btn inline-flex items-center px-4 py-6 text-sm font-medium rounded-s-lg hover:text-green-500 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:focus:ring-blue-500" data-url="{{ request.scheme }}://{{ request.get_host }}{{ image.image_file.url }}">
                            Copy Link
                        </button>       
                    <div style="padding-top: 10px; padding-bottom: 10px;"> <img src="{{ image.image_file.url }}" alt="{{ image.name }}" style="width: 100%;"/></div>
                    <div class="btn-group">
                        <form action="{% url 'delete_image' image.id %}" method="post" id="delete-form-{{ image.id }}">
                            {% csrf_token %}
                            <button type="button" class="delete-btn btn" onclick="confirmDelete('{{ image.name }}', 'delete-form-{{ image.id }}')">Delete</button>
                        </form>
                        <a href="{% url 'edit_image' image.id %}" class="edit-btn btn">Edit</a>
                        <a href="{{ image.image_file.url }}" class="download-btn btn" download>Download</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
        </div></div></div>
    <script>
        function confirmDelete(name, formId) {
            var confirmation = confirm("Are you sure you want to delete '" + name + "'?");
            if (confirmation) {
                document.getElementById(formId).submit();
            }
        }
        var copyButtons = document.querySelectorAll('.copy-btn');

copyButtons.forEach(function (button) {
    button.addEventListener('click', function () {
        var url = button.getAttribute('data-url');
        copyToClipboard(url);
    });
});

function copyToClipboard(text) {
    navigator.clipboard.writeText(text)
        .then(function () {
            alert('URL copied to clipboard!');
        })
        .catch(function (error) {
            console.error('Copy failed: ', error);
            alert('Failed to copy URL to clipboard!');
        });
}
    </script>
</body>
</html>
{% endblock %}

app/templates/app/login.html
{% extends "app/index1.html" %}
{% load crispy_forms_tags %}
{% block start %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ title }}</title>
    <style>
        /* Horizontally center the content */
        .justify-center {
            justify-content: center;
        }

        /* Vertically center the content */
        .items-center {
            align-items: center;
        }

        /* Add padding on the x-axis */
        .flex {
            display: flex;
            justify-content: center; /* Horizontally center the content */
            align-items: center; /* Vertically center the content */
        }

        /* Container styles */
        .container {
            width: 100%; /* Full width */
            max-width: 500px; /* Maximum width for larger screens */
            padding-top: 5%;
        }

        /* Style for the label */
        .label {
            display: block;
            margin-bottom: 5px;
            font-size: 14px;
            font-weight: bold;
        }

        /* Style for the input */
        .input {
            background-color: transparent;
            border: 1px solid #ced4da;
            border-radius: 0.25rem;
            font-size: 14px;
            padding: 10px;
            width: 100%;
            transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
        }

        /* Focus styles for the input */
        .input:focus {
            border-color: #80bdff;
            outline: 0;
            box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
        }
    </style>
</head>
<body>
    <div class="wrapper">
        <div class="content">
<div class="flex">
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            <h3>Login Here</h3>
            <div class="mb-3">
                <label for="username" class="label">Username:</label>
                <input type="text" id="username" name="username" class="input" placeholder="Enter your username" required>
            </div>
            <div class="mb-3">
                <label for="password" class="label">Password:</label>
                <input type="password" id="password" name="password" class="input" placeholder="Enter your password" required>
            </div>
            <button type="submit" class="btn">Login</button>
            <br><br>
            <a href="{% url 'password_reset' %}" class="btn">Forgot Password</a>
            <a href="{% url 'register' %}" class="btn">Don't have an account? Sign up</a>
        </form>
    </div>
</div>
        </div></div>
</body>
</html>

{% endblock start %}

app/templates/app/password_reset_complete.html
{% extends "app/index.html" %}
{% block start %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password change success</title>
    <style>
        /* Horizontally center the content */
        .justify-center {
            justify-content: center;
        }

        /* Vertically center the content */
        .items-center {
            align-items: center;
        }

        /* Add padding on the x-axis */
        .flex {
            display: flex;
            justify-content: center; /* Horizontally center the content */
            align-items: center; /* Vertically center the content */
             /* Make the container full height of the viewport */
        }

        /* Container styles */
        .container {
            width: 100%; /* Full width */
            max-width: 800px; /* Maximum width for larger screens */
            padding-top: 5%;
            text-align: center; /* Center text inside the container */
        }
    </style>
</head>
<body>
    <div class="wrapper">
        <div class="content">
    <div class="flex">
        <div class="container">
            <h4>Your password has been set. You may go ahead and</h4>
            <a href="{% url 'login' %}" class="btn">Login Here</a>
        </div>
    </div>
        </div></div>
</body>
</html>
{% endblock start %}

app/templates/app/privacyandpolicy.html
{% extends 'app/index.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% block start %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
</head>
<body>
    <center>
        <h1>
            This is Privacy & Policy page..!
        </h1>
    </center>
</body>
</html>
{% endblock start %}

app/templates/app/register.html
{% extends "app/index.html" %}

{% block start %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ title }}</title>
    <style>
        /* Add your custom CSS styles here */
        /* Horizontally center the content */
        .justify-center {
            justify-content: center;
        }

        /* Vertically center the content */
        .items-center {
            align-items: center;
        }

        /* Add padding on the x-axis */
        .flex {
            display: flex;
            justify-content: center; /* Horizontally center the content */
            align-items: center; /* Vertically center the content */
        }

        /* Container styles */
        .container {
            width: 100%; /* Full width */
            max-width: 500px; /* Maximum width for larger screens */
            padding-top: 3%;
        }

        /* Style for the label */
        .label {
            display: block;
            margin-bottom: 5px;
            font-size: 14px;
            font-weight: bold;
        }

        /* Style for the input */
        .input {
            background-color: transparent;
            border: 1px solid #ced4da;
            border-radius: 0.25rem;
            font-size: 14px;
            padding: 10px;
            width: 100%;
            transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
        }

        /* Focus styles for the input */
        .input:focus {
            border-color: #80bdff;
            outline: 0;
            box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
        }
    </style>
</head>
<body>
    <div class="wrapper">
        <div class="content">
<div class="flex">
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            <h3>Register Here</h3>
            {{ form.as_p }}
            <button class="btn" type="submit">Sign Up</button>
            <br><br>
            <a href="{% url 'login' %}" class="btn">Already have an account? Login</a>
        </form>
    </div>
</div>
        </div>
    </div>
</body>
</html>

{% endblock start %}

app/templates/app/upload_image.html
{% extends 'app/index.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% block start %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <style>
                /* Flex container */
        /* Horizontally center the content */
        .justify-center {
            justify-content: center;
        }

        /* Vertically center the content */
        .items-center {
            align-items: center;
        }

        /* Add padding on the x-axis */
        .flex {
            display: flex;
            justify-content: center; /* Horizontally center the content */
            align-items: center; /* Vertically center the content */
        }

        /* Container styles */
        .container {
            width: 100%; /* Full width */
            max-width: 500px; /* Maximum width for larger screens */
            padding-top: 3%;
        }

        /* Style for the label */
        .label {
            display: block;
            margin-bottom: 5px;
            font-size: 14px;
            font-weight: bold;
        }

        /* Style for the input */
        .input {
            background-color: transparent;
            border: 1px solid #ced4da;
            border-radius: 0.25rem;
            font-size: 14px;
            padding: 10px;
            width: 100%;
            transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
        }

        /* Focus styles for the input */
        .input:focus {
            border-color: #80bdff;
            outline: 0;
            box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
        }
    </style>
</head>
<body>    
    <div class="wrapper">
    <div class="content">
<div class="flex">
<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %} 
        <h2>Upload Image</h2>
        <div class="mb-3">
            <label for="id_name" class="label">Name:</label>
            <input type="text" id="id_name" name="name" class="input" placeholder="Enter your imagename" required>
        </div>
        <div class="mb-3">
            <label for="id_image" class="label">Image File:</label>
            <input type="file" id="id_image_file" name="image_file" class="input" placeholder="Upload your image" required>
        </div>
        <button class="btn" type="submit">Upload</button>
    </form>
</div></div></div></div>
</body>
</html>
{% endblock start %}

app/templates/app/upload_pdf.html
{% extends 'app/index.html' %}
{% load crispy_forms_tags %}
{% block start %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ title }}</title>
    <style>
        /* Flex container */
        /* Horizontally center the content */
        .justify-center {
            justify-content: center;
        }

        /* Vertically center the content */
        .items-center {
            align-items: center;
        }

        /* Add padding on the x-axis */
        .flex {
            display: flex;
            justify-content: center; /* Horizontally center the content */
            align-items: center; /* Vertically center the content */
        }

        /* Container styles */
        .container {
            width: 100%; /* Full width */
            max-width: 500px; /* Maximum width for larger screens */
            padding-top: 3%;
        }

        /* Style for the label */
        .label {
            display: block;
            margin-bottom: 5px;
            font-size: 14px;
            font-weight: bold;
        }

        /* Style for the input */
        .input {
            background-color: transparent;
            border: 1px solid #ced4da;
            border-radius: 0.25rem;
            font-size: 14px;
            padding: 10px;
            width: 100%;
            transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
        }

        /* Focus styles for the input */
        .input:focus {
            border-color: #80bdff;
            outline: 0;
            box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
        }
    </style>
</head>
<body>
    <div class="wrapper">
        <div class="content">
    <div class="flex">
        <div class="container">
            <form method="post" enctype="multipart/form-data">
                <h2>Upload PDF</h2>
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_title" class="label">File Name:</label>
                    <input type="text" id="id_title" name="title" class="input" placeholder="Enter your filename" required>
                </div>
                <div class="mb-3">
                    <label for="id_pdf_file" class="label">PDF File:</label>
                    <input type="file" id="id_pdf_file" name="pdf_file" class="input" placeholder="Upload your file" required>
                </div>
                <button type="submit" class="btn">Publish PDF</button>
            </form>
        </div>
    </div>
        </div></div>
</section>
</body>
</html>
{% endblock start %}